config/routes.rb
Ganjamap::Application.routes.draw do
  resources :products

  resources :carts

  resources :line_items

  resources :cofee_locs
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  post 'incoming_emails' => 'incoming_emails#create'

  root 'home#index', as: 'home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
end

app/controllers/home_controller.rb
#---
#       CS81 Project
#  Auth: DAWIT HAILE ACHAMYELHE
#   summer 2014
# 
# 
# 
#---


class HomeController < ApplicationController
    def index
        # BEGIN Simple but working search capabliy added by Dawit Haile
        if params[:search].present?
            @coffeshoplocs = CofeeLoc.near(params[:search], 10).order("created_at DESC")
            @coffeshoplocs if @ganjalocs.present?

        else
          @coffeshoplocs = CofeeLoc.all
        end

        @hash = Gmaps4rails.build_markers(@coffeshoplocs) do |coffeshop, marker|
            marker.lat coffeshop.latitude
            marker.lng coffeshop.longitude
            marker.title coffeshop.title
        end
        @coffeshoplocs = @coffeshoplocs.page(params[:page]).per_page(10)
    end

    def show
      @coffeshoplocs.all
    end
    
end

#  Work done by DAWIT HAILE ACHAMYELHE for CS81 Projects

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav_for_home.html.erb
<div class="navbar navbar-default container-fluid" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Cofeeshops', home_path, class: 'navbar-brand' %>
  </div>
  <div class="collapse navbar-collapse navbar-right">

    <% if signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Profile", current_user %></li>

          <li><a href="#"><i class="fa fa-coffee"></i>
          </a></li>


          <li><%= link_to signout_path, method: "delete" do %>
                <i class="fa fa-sign-out"></i>
            <% end %>
          </li>
        </ul>
    <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to "SIGNUP", signup_path%>
          </li>
          <li>
            <%= link_to signin_path, id: "Signin" do %>
                <i class="fa fa-user fa-lg"></i>
            <% end -%>
          </li>
        </ul>
    <% end %>
  </div>
</div>
<%= form_tag(@ganjaloc, method: "get", role: "form", id: "Ganjamap_form") do -%>
    <div class="row navbar-collapse collapse">
      <div class="col-lg-12">
        <div class="input-group">
          <%= search_field_tag 'search', params[:search], placeholder: "Search", class: "form-control" %>
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default" tabindex="-1">Search</button>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
              <li><a href="#">Deals</a></li>
              <li><a href="#">Zipcode</a></li>
              <li><a href="#">Lounge</a></li>
              <li class="divider"></li>
              <li><a href="#">Tour</a></li>
            </ul>
          </div>
        </div>
        <!-- /.input-group -->
      </div>
      <!-- /.col-lg-6 -->
    </div><!-- /.row -->
<% end -%>

app/views/home/_script.html.erb
<% content_for :script do %>
  
var mapStyle = [{"featureType":"landscape","stylers":[{"hue":"#FFA800"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.highway","stylers":[{"hue":"#53FF00"},{"saturation":-73},{"lightness":40},{"gamma":1}]},{"featureType":"road.arterial","stylers":[{"hue":"#FBFF00"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.local","stylers":[{"hue":"#00FFFD"},{"saturation":0},{"lightness":30},{"gamma":1}]},{"featureType":"water","stylers":[{"hue":"#00BFFF"},{"saturation":6},{"lightness":8},{"gamma":1}]},{"featureType":"poi","stylers":[{"hue":"#679714"},{"saturation":33.4},{"lightness":-25.4},{"gamma":1}]}];
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {zoom:      15,
      center:    new google.maps.LatLng(),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      styles:    mapStyle}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
     google.maps.event.trigger(map, "resize");
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    
  });


<% end %>
<!--this is needed so that the gmaps4rails library works smooth-->

app/views/home/_table_for_home.html.erb
<table class="table table-responsive table-bordered table-condensed">
  <thead>
    <tr>
      
      <th>Address</th>
      
    </tr>
  </thead>

  <tbody>
  
    <% @coffeshoplocs.each do |coffeshoploc| %>
      <tr>
        
        <td><%= coffeshoploc.address %></td>
           
      </tr>
    <% end %>
  </tbody>
</table>
<!-- Work done by DAWIT HAILE ACHAMYELHE -->

app/views/home/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript">

</script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript">

</script>
<!--
#  * Created by Dawit Haile Achamyelhe for CS83 - Server-Side Ruby Web Programming*
#
#
#  Fall 2014
# 
# 
# -->
<!--The above is needed for the google API-->

<!--    Navigation Markup start for home page here-->

<%= render "nav_for_home" %>
<div id="toggle"><%= render "table_for_home" %></div>

<!--container for google Map & left and right section-->
<div class="container-fluid">
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<!--End of container for google Map-->

<div class="row bootom-Ganjamap">

  <div class="col-md-4">
    <div class="panel">

      <div class="panel-body">
        <%= render "table_for_home" %>
      </div>
      <div class="panel-heading pagination-sm pagination">
        <%= will_paginate @coffeshoplocs, :container => false %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel">
      <div class="panel-heading">
        <h4> Making Coffee in Ethiopia </h4>
      </div>
      <div class="panel-body">
        <iframe width="400" height="415" src="//www.youtube.com/embed/qQpdhyqjklM" style="border:none;" allowfullscreen>

        </iframe>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="well">
      <p>According to legend, ancestors of today's Oromo people were believed to have been the first to recognize the
        energizing effect of the coffee plant,[5] though no direct evidence has been found indicating where in Africa
        coffee grew or who among the native populations might have used it as a stimulant or even known about it,
        earlier than the 17th century.[5] The story of Kaldi, the 9th-century Ethiopian goatherder who discovered coffee
        when noticed how excited his goats became after eating the beans from a coffee plant</p>

    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="unstyled center list-circle-icons list-circle-icons-small">
          <li>
            <a href="#none" title="Like us on Facebook" data-rel="tooltip" data-toggle="tooltip"><span class="fa fa-facebook"></span></a>
          </li>
          <li>
            <a href="#none" title="Follow us on Twitter" data-rel="tooltip" data-toggle="tooltip"><span class="fa fa-twitter"></span></a>
          </li>
          <li>
            <a href="#none" title="Follow us on Pinterest" data-rel="tooltip" data-toggle="tooltip"><span class="fa fa-pinterest"></span></a>
          </li>
          <li>
            <a href="#none" title="Follow us on Google Plus" data-rel="tooltip" data-toggle="tooltip"><span class="fa fa-google-plus"></span></a>
          </li>
          <li>
            <a href="#none" title="View Flickr Gallery" data-rel="tooltip" data-toggle="tooltip"><span class="fa fa-flickr"></span></a>
          </li>
        </ul>
        <ul class="list-inline">
          <li><a href="index.html">Home</a></li>
          <li><a href="features.html">Features</a></li>
          <li><a href="portfolio-parent.html">Portfolio</a></li>
          <li><a href="blog-parent.html">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>
          <li><a href="user-signup.html">Sign Up</a></li>
          <li><a href="user-login.html">Login</a></li>
        </ul>
        <p>&copy;2014. CofeeMap. BY DAWIT HAILE ACHAMYELHE</p>

      </div>
      <!-- end col -->
    </div>
    <!-- end row fluid -->
  </div>
  <!-- end container -->
</footer>